### ISSUE TITLE
Filter Aliexpress search results by store name (regex/glob)

### ISSUE THREAD

**Issue by sammcj** [letsblockit/letsblockit#495]
### What website(s) would this filter apply to?

https://aliexpress.com

### What content should be blocked?

Often fake stores will popup and flood Aliexpress search results with dodgy results, the good news is these usually have highly predictable store names.

Using the following filter I can block

### What options should be offered?

A regex or pattern to match for the store names.

A default could be `(/Shop\d+ Store/)` which catches a huge amount of fake generated stores currently flooding the site.

### Did you write a custom uBlock filter already?

Yes!

```
! https://www.aliexpress.com filter out fake generated stores such as "Shop 12345 Store"
www.aliexpress.com##a.search-card-item[class*="cards--gallery--"][class*="manhattan--container--"]:has-text(/Shop\d+ Store/)
```

### Additional notes

Looking at the existing templates, I suspect something like this:

```yaml
title: "AliExpress: filter out results by store name"
contributors:
  - sammcj
params:
  - name: pattern
    description: Regex or patterns to match store names
    type: list
    default: [ "Shop \d+ Store" ]
tags:
  - youtube
template: |
  {{#each pattern}}
  www.aliexpress.com##a.search-card-item[class*="cards--gallery--"][class*="manhattan--container--"]:has-text(/\b{{this}}\b/i)
```

But would need tests etc...

**Comment by xvello** [comment]
Hello @sammcj, thanks for the suggestion!

I think this template would fit right in within the scope of this project! A couple of things though:

1/ I have been working on [a new "regex or word" parameter type](https://github.com/letsblockit/letsblockit/pull/352) that would be very helpful for that template and the Amazon one. We can get it started with only regexps for now and transition later.

2/ I prefer to avoid using the `:has-text` selector for two reasons:
  - it's performance is lower than matching on an attribute, as it's implemented in javascript instead of CSS
  - it encourages matching on display strings, which break on different languages. More than half of our active users live in non-english-speaking countries. 

In this case, the store name is not available as an attribute, so we need to use `:has-text`, but should scope its search scope as small as possible, which is the `<a>` element. I think the following rule works best:

```adblock
aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text(/Shop\d+ Store/):upward(a.search-card-item)
```

- Applies on all `*.aliexpress.com` subdomains, for example I'm redirected to `fr.aliexpress.com`
- Scopes the rule to children of the div with the `card-list` ID. We might need to me more specific to make sure we only match search pages
- Look for links with one class name starting with `cards--storeLink-`, then match its text
- If matching, go up to find the parent link with the `search-card-item` class and hide it

You are right about what the final YAML would look like. Would you like to try out opening a PR? I'd start by copying https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/amazon-products.yaml into a new `aliexpress-shops.yaml` file and changing the template, tests, and description accordingly. If there's validation errors we can patch it up together.

**Comment by JohnyP36** [comment]
@sammcj you can open an PR yourself if you want. I made already the template, but you should check it yourself and change if something is incorrect.

```yaml
title: "AliExpress: filter out results by store name"
contributors:
  - JohnyP36
  - sammcj
  - xvello
params:
  - name: store-name
    description: Rules to hide search results which belongs to a certain store name
    type: list
    default: [ ]
    presets:
      - name: fake-stores
        description: Hide products from fake stores (starting with "Shop" and ending with "Store") 
        values:
          - '/Shop \d+ Store/'
tags:
  - aliexpress
template: |
  {{#each store-name}}
  aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text({{{this}}}):upward(a.search-card-item)
  {{/each}}
tests:
  - params:
      store-name:
        - "/shop/i"
        - "NAME"
    output: |
      aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text(/shop/i):upward(a.search-card-item)
      aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text(NAME):upward(a.search-card-item)
  - params: {}
    output: ""
---

This filter template allows you to hide products from selected stores from the AliExprees. It comes with some presets
that might be useful for you, at the bottom of the parameters.

Instead of simple word matching, this template uses Regular Expressions to reduce the risk of false positives.
You should [read this documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)
to learn the syntax, but the following examples should help you get started:

- You can specify any sequence of characters that will be searched in the store name of the product. For example:
    - `/Echo Show/` will match the products of the store name `Echo Show 8`, but not the `Echo Dot`
    - `/Store/` will match `Store Hammock`, but also `Storehouse`
- For a case-insensitive search, simply add `i` at the end of your expression. For example:
    - `/shop/i` will match both `Shop`, `shop` and `SHOP`
- To make sure you match on the exact word, you should use the `\b` "word boundary" matcher. For example:
    - `/\bstore\b/i` will match `Store Food`, but not `Storehouse` or `superstore`
- You can also use other operators for a better match, for example
    - `/\bstore(s)?\b/i` will match both occurrences of singular `Store`, but also the plural `Stores`


You can test your rules at [regex101](https://regex101.com/).
```

**Comment by sammcj** [comment]
Thanks folks! I’ll submit a PR early next week when I’m back in town.

**Comment by sammcj** [comment]
Sorry running way behind this week - I'll probably do this in the weekend as work is crazy. If the issue is an eyesore feel free to close it but I'll still submit a PR for consideration.

**Comment by JohnyP36** [comment]
> Sorry running way behind this week - I'll probably do this in the weekend as work is crazy. If the issue is an eyesore feel free to close it but I'll still submit a PR for consideration.

No worries, we will wait. 
As you don't have must time you can just copy-paste **and check** the template I proposed in https://github.com/letsblockit/letsblockit/issues/495#issuecomment-1625179917 *(or see below)*.

<details><summary>aliexpress-shops.yaml</summary>

```yaml
title: "AliExpress: filter out results by store name"
contributors:
  - JohnyP36
  - sammcj
  - xvello
params:
  - name: store-name
    description: Rules to hide search results which belongs to a certain store name
    type: list
    default: [ ]
    presets:
      - name: fake-stores
        description: Hide products from fake stores (starting with "Shop" and ending with "Store") 
        values:
          - '/Shop \d+ Store/'
tags:
  - aliexpress
template: |
  {{#each store-name}}
  aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text({{{this}}}):upward(a.search-card-item)
  {{/each}}
tests:
  - params:
      store-name:
        - "/shop/i"
        - "NAME"
    output: |
      aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text(/shop/i):upward(a.search-card-item)
      aliexpress.com###card-list a[class^="cards--storeLink-"]:has-text(NAME):upward(a.search-card-item)
  - params: {}
    output: ""
---

This filter template allows you to hide products from selected stores from the AliExprees. It comes with some presets
that might be useful for you, at the bottom of the parameters.

Instead of simple word matching, this template uses Regular Expressions to reduce the risk of false positives.
You should [read this documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)
to learn the syntax, but the following examples should help you get started:

- You can specify any sequence of characters that will be searched in the store name of the product. For example:
    - `/Echo Show/` will match the products of the store name `Echo Show 8`, but not the `Echo Dot`
    - `/Store/` will match `Store Hammock`, but also `Storehouse`
- For a case-insensitive search, simply add `i` at the end of your expression. For example:
    - `/shop/i` will match both `Shop`, `shop` and `SHOP`
- To make sure you match on the exact word, you should use the `\b` "word boundary" matcher. For example:
    - `/\bstore\b/i` will match `Store Food`, but not `Storehouse` or `superstore`
- You can also use other operators for a better match, for example
    - `/\bstore(s)?\b/i` will match both occurrences of singular `Store`, but also the plural `Stores`


You can test your rules at [regex101](https://regex101.com/).
```

<details>
